namespace MyApp.Domain.Entities
{
    public class User : BaseEntity
    {
        public string Username { get; set; }
        public string Email { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public bool IsTwoFactorEnabled { get; set; }

        // Add these properties for two-factor authentication
        public string TwoFactorCode { get; set; } // Temporary 2FA code, often generated by an authenticator app

        public string TwoFactorRecoveryCode { get; set; } // Recovery code in case the user can't access their 2FA device
    }
}